# Generated by Django 4.0.1 on 2023-02-23 02:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledata',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None), size=None),
        ),
    ]
