version: "3.9"
services:
  api:
    image: chadmowbray/ml-backend-prod:$NEW_VERSION 
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
  nginx:
    image: chadmowbray/ml-webserver-prod:$NEW_VERSION
    restart: always
    ports:
      - "80:80"
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
volumes:
  postgres_data: